<?php get_header(); ?>
<main class="alutem-home">
	<section class="hero" id="anasayfa">
		<div class="hero-img"></div><div class="hero-overlay"></div>
		<div class="hero-side-note">MİMARİ CEPHE SİSTEMLERİ <span>—</span> ZM CEPHE</div>
		<div class="hero-copy"><span class="hero-eyebrow">ZM CEPHE · ALÜMİNYUM CEPHE SİSTEMLERİ</span><h1>MİMARİNİN<br><span>GÜCÜNÜ</span><br>HİSSEDİN</h1><a href="<?php echo esc_url( zm_cephe_page_url( 'sistemler' ) ); ?>" class="hero-link">SİSTEMLERİMİZİ KEŞFEDİN <b>↗</b></a></div>
		<div class="hero-foot"><span>TASARIMDAN UYGULAMAYA</span><span class="line"></span><span>01 — 04</span></div>
		<a class="scroll" href="#home-highlights">AŞAĞI İN <b>↓</b></a>
	</section>
	<section class="home-highlights" id="home-highlights"><div class="highlight-label">ZM CEPHE YAKLAŞIMI</div><div><b>01</b><span>Proje odaklı<br>çözümler</span></div><div><b>02</b><span>Detaylı teknik<br>planlama</span></div><div><b>03</b><span>Nitelikli<br>uygulama</span></div><div><b>04</b><span>Uçtan uca<br>iş birliği</span></div></section>
	<section class="home-system-intro section"><div class="home-section-heading"><span class="kicker dark"><i></i> MİMARİ SİSTEMLER</span><h2>Yapınız için<br><em>doğru sistem.</em></h2></div><p>Her yapının mimarisine, kullanım amacına ve teknik beklentilerine özel alüminyum cephe çözümleri geliştiriyoruz.</p></section>
	<section class="home-system-grid">
		<?php $systems = array( array( 'Giydirme Cephe Sistemleri', '1486406146926-c627a92ad1ab', '01', 'giydirme' ), array( 'Alüminyum Doğrama', '1600607687939-ce8a6c25118c', '02', 'dograma' ), array( 'Kapı & Pencere Sistemleri', '1511818966892-d7d671e672a2', '03', 'kapi-pencere' ), array( 'Özel Cephe Uygulamaları', '1487958449943-2429e8be8625', '04', 'ozel' ) ); foreach ( $systems as $system ) : ?>
		<a class="home-system-card" href="<?php echo esc_url( zm_cephe_page_url( 'sistemler' ) . '#' . $system[3] ); ?>"><img src="https://images.unsplash.com/photo-<?php echo esc_attr( $system[1] ); ?>?auto=format&amp;fit=crop&amp;w=1000&amp;q=85" alt="<?php echo esc_attr( $system[0] ); ?>"><span class="home-system-no"><?php echo esc_html( $system[2] ); ?></span><span class="home-system-name"><?php echo esc_html( $system[0] ); ?><b>↗</b></span></a>
		<?php endforeach; ?>
	</section>
	<section class="home-about">
		<div class="home-about-image"><img src="https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&amp;fit=crop&amp;w=1500&amp;q=85" alt="Modern mimari cephe uygulaması"><span>ZM CEPHE / MİMARİ SİSTEMLER</span></div>
		<div class="home-about-copy"><span class="kicker light"><i></i> HAKKIMIZDA</span><h2>Güçlü adımlarla<br><em>ilerliyoruz.</em></h2><p>Alüminyum cephe sistemleri ve mimarlık alanındaki deneyimimizi; projeye özel yaklaşım, titiz detay çözümü ve nitelikli uygulama anlayışıyla bir araya getiriyoruz.</p><p>İlk fikirden uygulama sürecine kadar, yapının ihtiyaçlarına uygun çözümler için iş ortaklarımızla birlikte çalışıyoruz.</p><a class="home-about-link" href="<?php echo esc_url( zm_cephe_page_url( 'hakkimizda' ) ); ?>">ZM CEPHE’Yİ TANIYIN <b>↗</b></a></div>
	</section>
	<section class="home-belief"><div class="belief-head"><span class="kicker dark"><i></i> TASARIMDAN UYGULAMAYA</span><h2>İyi cephe,<br><em>iyi detaylarda.</em></h2></div><div class="belief-copy"><p>Bir yapının cephesi; estetik, konfor ve performansı bir arada taşımalı. Doğru malzeme ve doğru detaylarla, mimari fikri uzun ömürlü bir çözüme dönüştürüyoruz.</p><a href="<?php echo esc_url( zm_cephe_page_url( 'hakkimizda' ) ); ?>" aria-label="Çalışma yaklaşımımız">↗</a></div><div class="belief-image"><img src="https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&amp;fit=crop&amp;w=1900&amp;q=85" alt="Cam ve alüminyum cephe detayı"><span>DETAY / MALZEME / IŞIK</span></div></section>
	<section class="home-services"><div class="section"><div class="home-section-heading"><span class="kicker dark"><i></i> NASIL ÇALIŞIYORUZ?</span><h2>Fikirden sahaya<br><em>birlikte.</em></h2></div><div class="service-teasers"><article><span>01 / KEŞİF</span><h3>İhtiyacı<br>anlıyoruz.</h3><p>Projenin beklentilerini, mimari dilini ve teknik koşullarını birlikte değerlendiriyoruz.</p></article><article><span>02 / TASARIM</span><h3>Detayları<br>çözüyoruz.</h3><p>Uygun sistem alternatiflerini ve teknik detayları proje özelinde planlıyoruz.</p></article><article><span>03 / UYGULAMA</span><h3>Özenle<br>hayata geçiriyoruz.</h3><p>Planlanan cephe çözümünü sahada kalite ve koordinasyon odağıyla uyguluyoruz.</p></article><article><span>04 / TESLİM</span><h3>Sonuca<br>birlikte ulaşıyoruz.</h3><p>Süreç boyunca iletişimde kalarak uygulamanın tamamlanmasını takip ediyoruz.</p></article></div></div></section>
	<section class="project-section home-projects"><div class="section project-inner"><div class="section-top"><div><span class="kicker dark"><i></i> PROJE SEÇKİSİ</span><h2>Mimariyle<br><em>birlikte.</em></h2></div><p>Farklı ölçek ve ihtiyaçlara göre tasarlanan cephe uygulamalarını inceleyin.</p></div><div class="project-grid"><?php $projects = new WP_Query( array( 'post_type' => 'zm_proje', 'posts_per_page' => 6, 'post_status' => 'publish' ) ); if ( $projects->have_posts() ) : while ( $projects->have_posts() ) : $projects->the_post(); get_template_part( 'template-parts/project-card' ); endwhile; wp_reset_postdata(); else : ?><a class="home-project-placeholder" href="<?php echo esc_url( zm_cephe_page_url( 'projeler' ) ); ?>"><img src="https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&amp;fit=crop&amp;w=1500&amp;q=85" alt="Modern ticari yapı cephesi"><span>PROJE SEÇKİSİ</span><strong>Projelerimiz<br>yakında burada.</strong><b>PROJELERİ GÖRÜN ↗</b></a><a class="home-project-placeholder" href="<?php echo esc_url( zm_cephe_page_url( 'projeler' ) ); ?>"><img src="https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&amp;fit=crop&amp;w=1200&amp;q=85" alt="Modern mimari yapı"><span>ZM CEPHE</span><strong>Her yapıya<br>özel çözüm.</strong><b>PROJE SÜRECİMİZ ↗</b></a><?php endif; ?></div><a class="text-link" href="<?php echo esc_url( zm_cephe_page_url( 'projeler' ) ); ?>">Tüm projeleri görün <span>↗</span></a></div></section>
	<section class="home-reference"><div class="reference-image"></div><div class="reference-copy"><span class="kicker light"><i></i> BU İŞİ SEVİYORUZ</span><h2>Güç ve<br><em>estetik.</em></h2><p>ZM Cephe olarak dış cephe ve mimari sistemler alanında, tasarım ve detay çözümünden uygulamaya kadar her aşamada proje ortaklarımızın yanında yer alıyoruz.</p><p>Her projede doğru sistemi birlikte belirliyor; yapının karakterini yansıtan, işlevli ve uzun ömürlü çözümler için çalışıyoruz.</p><a href="<?php echo esc_url( zm_cephe_page_url( 'iletisim' ) ); ?>">PROJENİZİ KONUŞALIM <b>↗</b></a></div></section>
	<section class="cta"><div class="cta-bg"></div><div class="cta-content"><span class="kicker light"><i></i> ZM CEPHE İLE İLETİŞİME GEÇİN</span><h2>Birlikte<br><em>hayata geçirelim.</em></h2><div><p>Projeniz için doğru cephe çözümünü arıyorsanız bize ulaşın.</p><a href="<?php echo esc_url( zm_cephe_page_url( 'iletisim' ) ); ?>">İLETİŞİME GEÇİN <b>↗</b></a></div></div></section>
</main>
<?php get_footer(); ?>
